### ISSUE TITLE
Tracking features for RDA checks

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/FAIR_eva#108]
### RDA-A1-01M 

- [ ] Values for `downloadURL` and `DOI` (80/100)
- [ ] Value for `license` (10/100)
- [ ] `license` in SPDX (10/100)
- [ ] Uses new `ConfigTerms` decorator
