### ISSUE TITLE
Tracking features for RDA checks: Reusabilty

### ISSUE THREAD

**Issue by PalomoIFCA** [EOSC-synergy/FAIR_eva#116]
### RDA-R1-01M
- [ ] Checks the existance of disciplinar terms 
- [ ] Check the list of terms in order to make sure they are the correct ones

### RDA-R1.1-01M

- [ ] Copy the already done r1.1-02m
